/** Optional tool labels shared by the standalone editor and embeddings. */
import type { BlueprintEditorLabels } from './editor.js';

export const blueprintToolsZh: NonNullable<BlueprintEditorLabels['tools']> = {
    search: "搜索节点、备注与关联资料",
    clearSearch: "清除搜索",
    noResults: "没有找到匹配内容",
    expandAll: "全部展开",
    collapseAll: "全部折叠",
    collapseToLevel: "显示到层级",
    shortcuts: "选中节点后：Enter 添加同级 · Tab 添加子模块 · F2 重命名 · 方向键导航 · Esc 取消；双击节点编辑",
    links: "关联资料",
    webLink: "网页链接",
    nodeLink: "关联节点",
    noteLink: "关联笔记",
    url: "网页地址",
    linkTitle: "链接标题（可选）",
    addLink: "添加关联",
    removeLink: "移除关联",
    missingLink: "原节点已删除",
    invalidUrl: "请输入有效的 HTTP 或 HTTPS 网页地址",
    notebook: "生成笔记目录",
    notebookHelp: "导入 JSON 笔记列表，按分组生成目录；再次点击为当前笔记列表生成目录",
    invalidNotebook: "笔记列表无效，请使用包含 title 和 notes 的 JSON，笔记须有唯一 id 和 title，链接须为 HTTP(S)",
    noteSnapshot: "已保留笔记快照",
    results: count => `找到 ${count} 个节点`,
};

export const blueprintToolsEn: NonNullable<BlueprintEditorLabels['tools']> = {
    search: "Search nodes, notes and references",
    clearSearch: "Clear search",
    noResults: "No matching content",
    expandAll: "Expand all",
    collapseAll: "Collapse all",
    collapseToLevel: "Show through level",
    shortcuts: "Select a node: Enter adds a sibling · Tab adds a child module · F2 renames · Arrow keys navigate · Esc cancels; double-click to edit",
    links: "References",
    webLink: "Web link",
    nodeLink: "Link a node",
    noteLink: "Link a note",
    url: "Web address",
    linkTitle: "Link title (optional)",
    addLink: "Add reference",
    removeLink: "Remove reference",
    missingLink: "Original node deleted",
    invalidUrl: "Enter a valid HTTP or HTTPS web address",
    notebook: "Generate note directory",
    notebookHelp: "Import a JSON notebook to generate a grouped directory; click again to generate from the current notebook",
    invalidNotebook: "Invalid notebook: expected title and notes, unique note ids and titles, and HTTP(S) links",
    noteSnapshot: "Note snapshot retained",
    results: count => `${count} matching nodes`,
};
